# -*- coding: utf-8 -*-
"""
/***************************************************************************
 land_purpose_useplan
                                 A QGIS plugin
 지목과 토지이용계획을 가져오는 플러그인
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-16
        copyright            : (C) 2025 by LCY부동산중개법인
        email                : lcy5002@naver.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load land_purpose_useplan class from file land_purpose_useplan.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .land_purpose_useplan import land_purpose_useplan
    return land_purpose_useplan(iface)
